### ISSUE TITLE
How can i use Logical operators ?

### ISSUE THREAD

**Issue by chomwitt** [gusnan/devilspie2#12]
For example the following code didnt work.

if (get_application_name()=="Document Viewer" or get_application_name()=="Okular" ) then
   -- x,y, xsize, ysize
   set_window_geometry2(0,0,800,800);
   pin_window();
   minimize();
end

**Comment by gusnan** [comment]
What exactly does get_application_name() return in your case? Could you add a 
print("application name: " .. get_application_name());

before the if-case, and then run devilspie2 with --debug and --emulate, and find what is returns on the Okular window?

**Comment by chomwitt** [comment]
It was  'Okular' the app name (quotes included).  So it works now. Thanks.

Is there a way to make the syntax shorter?  
get_application_name()==("Document Viewer" or "'Okular'")  wont work.

**Comment by gusnan** [comment]
You could do something like
g=get_application_name()
if (g=="Document Viewer" or g=="'Okular'") then
end
But that really is more of a Lua problem than a devilspie2 one... Closing this issue now.
Please open it again if you have more problems with this issue. (Or open another one if you have other).
