### ISSUE TITLE
Are lua script changes whlie an instance is running used?

### ISSUE THREAD

**Issue by chomwitt** [gusnan/devilspie2#13]
If i interpret some test rigth it seems the devilspie2 wont take notice of changes to lua scripts while it's running but only if we kill it and run it again.

Can we make the new changes in lua scripts take immediate effect in a running instance?

**Comment by gusnan** [comment]
This functionaity is already present in the lastest git, and you will have it in the coming 0.28 version.

**Comment by chomwitt** [comment]
ok. thanks.
