### ISSUE TITLE
Unexpected window positioning with undecorate_window and set_window_position

### ISSUE THREAD

**Issue by schmich** [gusnan/devilspie2#2]
My devilspie2 script:

``` lua
if (get_application_name() == "gnome-calculator") then
  undecorate_window()
  set_window_position(0, 0)
end
```

I'm not sure what the intended behavior is, but with this configuration, when I run gnome-calculator, the window appears offset below where I expect. I expect the top-left visible portion of the window to be at (0, 0). My hypothesis is that `set_window_position` does not take into account the updated window geometry after doing `undecorate_window`. I observed this on Fluxbox, but I imagine it is an issue with other window managers as well.

For reference, this scenario behaves as expected with devilspie and the following script:

``` lisp
(if
  (matches (application_name) "gnome-calculator")
  (begin
    (undecorate)
    (geometry "+0+0")
  )
)
```

For both devilspie and devilspie2, the xwininfo-reported upper-left corner is at (0, 0), but the window sizes are different, with the difference probably being the size of the window decoration.

devilspie2:

```
foo@bar:~/.devilspie$ xwininfo -name Calculator

xwininfo: Window id: 0xe00006 "Calculator"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 312
  Height: 215
  Depth: 24
  Visual: 0x24
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x21 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsUnMapped
  Override Redirect State: no
  Corners:  +0+0  -1608+0  -1608-985  +0-985
  -geometry 312x215+0+0
```

devilspie:

```
foo@bar:~/.devilspie$ xwininfo -name Calculator

xwininfo: Window id: 0xe00006 "Calculator"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 314
  Height: 239
  Depth: 24
  Visual: 0x24
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x21 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +0+0  -1606+0  -1606-961  +0-961
  -geometry 314x239+0+0
```

Version info:
Linux 3.2.0-23-virtual #36-Ubuntu SMP Tue Apr 10 22:29:03 UTC 2012 x86_64 x86_64 GNU/Linux
Fluxbox 1.3.2 : (c) 2001-2011 Fluxbox Team
Devilspie2 v0.15
Devil's Pie 0.22

If I get a chance, I'll dig through the code and submit a patch.

Thanks for your work on this project,
Chris

**Comment by gusnan** [comment]
I havn't looked at it in detail, but the implementation of it in devilspie is availible here:
https://github.com/plaes/devilspie/blob/work/src/actions.c#L173
I would gladly accept a patch.

**Comment by gusnan** [comment]
I've added set_window_geometry2, which should give results more like the original devispie - it uses XMoveResizeWindow, instead of wnck_window_set_geometry.

**Comment by gusnan** [comment]
hmm, wait a minute - I should make a set_window_position alternative too. Sorry for being too much in a hurry to close.
