### ISSUE TITLE
Close window. How?

### ISSUE THREAD

**Issue by stegrams** [gusnan/devilspie2#23]
I m newbie to Lua's version of devilspie, actually I have'nt used it yet, but I cant find a command to close the target window (i.e. to emulate in script the [x] button click).

Is it currently feasible to achieve that action?

Thanks in advanced

**Comment by gusnan** [comment]
You are indeed right, I seem to have missed functions to close windows... I'll get right to it.

**Comment by stegrams** [comment]
That was quick!! I really appreciate this :>

**Comment by gusnan** [comment]
Please try this out, and reopen this issue if it doesn't work.

**Comment by stegrams** [comment]
`close_window()` works just great!! No need to reopen. Thanks for your response
