### ISSUE TITLE
bundle lua

### ISSUE THREAD

**Issue by hasufell** [gusnan/devilspie2#35]
This is a delicate matter. Usually I am raging against anyone who bundles libraries which should be shipped by distributions only (performance, security, bugfixing etc).

But... lua is one of these libraries which are heavily hacked by downstream maintainers since lua upstream isn't collaborative at all. That causes so many problems that I gave up relying on the lua version which is shipped in gentoo.

I think it would make sense to do the following
- tweak the build system a bit so it has an _optional_ switch to build and use a bundled lua version which is then linked statically
- distribute a tarball which has a lua version bundled which is confirmed to work with devilspie2 (BUT: don't add lua code to this repository, only to the release tarballs!)

That would make it easier for people who don't want to rely on system lua any more. I could help with the build system adjustments if necessary.

**Comment by gusnan** [comment]
Please post on the Savannah mailinglist or issue tracker, I have abandoned github - no updates will be made to this git repository. 
Oh, now I noticed that you already have done so. Thanks!
