### ISSUE TITLE
action when window is [un]minimized

### ISSUE THREAD

**Issue by brianjmurrell** [gusnan/devilspie2#38]
It would be interesting to be able to take actions when a window's state, such as [un-]minimized changes.

For example, one could then only list minimized windows in one's tasklist by using `set_skip_tasklist()` when the minimised state changes.

**Comment by Frenzie** [comment]
Note that this repo is abandoned. I think the mailing list is probably the best option https://lists.nongnu.org/mailman/listinfo/devilspie2-discuss

**Comment by brianjmurrell** [comment]
Ahh.  Yes.  I see.  Might be useful to remove the ability to create new issues, if possible.  If not, maybe just remove the _issues_ capability altogether.  I have seen other projects that don't have the _issues_ capability so that must be doable.
