### ISSUE TITLE
Match substring in window title

### ISSUE THREAD

**Issue by chomwitt** [gusnan/devilspie2#8]
Is there an option to match a substring or regex of windows titles?

**Comment by gusnan** [comment]
The functionality is available in Lua itself: See http://lua-users.org/wiki/StringLibraryTutorial and http://lua-users.org/wiki/PatternsTutorial for some examples.
(You can do something like 
if (string.find(get_application_name(),"what_to_search_for")~=nil) then
and it should work just fine - the links I gave should give you all information you'll need to make the required expressions)

**Comment by chomwitt** [comment]
thanks

**Comment by chomwitt** [comment]
Do you plan to create a 'contains' command like in devilspie ?

**Comment by gusnan** [comment]
Not really... Its kind of a special case when you need a substring of a window title - then I would also need to make a similar function for the window name, and perhaps the window instance... That would amount in pretty many functions, which I find unnecessary when you could use string.find to solve a similar problem on all these cases. 
Also - you kind define a function like that a put it in your local devilspie2.lua, and it would be found and usable in all your devilspie2 scripts.

**Comment by hansbkk** [comment]
Well the author of the original devilspie did have a 'contains' function for matches. IMO not a critical thing, but then I also don't agree matching on substrings is such a special case, and many (most) end-users don't want to get into lua programming for (IMO) such basic functionality. But of course it's your project, and let me take the opportunity to thank you for your work, it is a fine UX-improvement tool, especially given it works across so many DE/wm platforms, (in my case currently working pretty well on Gala (mutter?)/Pantheon with elementaryOS 'Luna'.

Sure wish wmctrl were also still being actively maintained as well, having to use devilspie2 for ad-hoc window control is a bit of a kludge.
