### ISSUE TITLE
Differences in geometry between declared and xwinfo

### ISSUE THREAD

**Issue by chomwitt** [gusnan/devilspie2#9]
if (string.find(get_application_name(),"Firefox")~=nil) then
   -- x,y, xsize, ysize
   set_window_geometry(0,0,500,500);
        set_window_workspace(3);
end

but xwinfo gives:
  Absolute upper-left X:  8
  Absolute upper-left Y:  44
  Relative upper-left X:  4
  Relative upper-left Y:  22
  Width: 492
  Height: 474
.......
.......
  Corners:  +8+44  -1420+44  -1420-682  +8-682
  -geometry 492x474+4+22

What explains those differnces?

**Comment by gusnan** [comment]
Which version are you using? - Could you please try with set_window_geometry2(x,y,xsize,ysize)?  (Notice the 2 at the end of the function name.) It is available in devilspie2 version 0.21 and later.

The difference is that set_window_position2 uses XMoveWindow from the X library, while set_window_position uses the wnck function wnck_window_set_geometry.

**Comment by chomwitt** [comment]
I use the latest deb package (v0.28) although it says 0.20 in the site. 
With geometry2  xwinfo gives the declared sizes.
thanks.

**Comment by gusnan** [comment]
Great! Closing this issue then.
